from travel_agent.tools.base import BaseMockTool


class FlightTool(BaseMockTool):
    """航班查询工具，根据用户的旅行需求返回航班选项。"""

    domain = "flights"
    description = "航班查询工具，根据用户的旅行需求，返回 suitable_flights"

    async def execute(
        self,
        destination: str,
        start_date: str,
        end_date: str,
        budget: float,
        num_travelers: int,
        **kwargs: object,
    ) -> list[dict]:
        seed = self._get_seed(
            destination=destination,
            start_date=start_date,
            end_date=end_date,
            budget=budget,
            num_travelers=num_travelers,
        )
        return self._select_options(_FLIGHT_POOL, seed, count=3)


_FLIGHT_POOL = [
    {
        "flight_no": "CA1501",
        "airline": "中国国际航空",
        "departure_time": "08:30",
        "arrival_time": "10:50",
        "departure_city": "上海",
        "arrival_city": "北京",
        "price": 1280,
        "stops": 0,
        "duration": "2h20m",
    },
    {
        "flight_no": "CA1831",
        "airline": "中国国际航空",
        "departure_time": "17:00",
        "arrival_time": "19:20",
        "departure_city": "上海",
        "arrival_city": "北京",
        "price": 1050,
        "stops": 0,
        "duration": "2h20m",
    },
    {
        "flight_no": "MU5165",
        "airline": "中国东方航空",
        "departure_time": "07:45",
        "arrival_time": "09:30",
        "departure_city": "北京",
        "arrival_city": "杭州",
        "price": 980,
        "stops": 0,
        "duration": "1h45m",
    },
    {
        "flight_no": "MU5101",
        "airline": "中国东方航空",
        "departure_time": "13:20",
        "arrival_time": "15:25",
        "departure_city": "北京",
        "arrival_city": "上海",
        "price": 1100,
        "stops": 0,
        "duration": "2h05m",
    },
    {
        "flight_no": "CZ3501",
        "airline": "中国南方航空",
        "departure_time": "09:00",
        "arrival_time": "12:10",
        "departure_city": "广州",
        "arrival_city": "北京",
        "price": 1680,
        "stops": 0,
        "duration": "3h10m",
    },
    {
        "flight_no": "CZ6151",
        "airline": "中国南方航空",
        "departure_time": "14:50",
        "arrival_time": "17:40",
        "departure_city": "广州",
        "arrival_city": "成都",
        "price": 1350,
        "stops": 0,
        "duration": "2h50m",
    },
    {
        "flight_no": "HU7667",
        "airline": "海南航空",
        "departure_time": "06:30",
        "arrival_time": "10:10",
        "departure_city": "北京",
        "arrival_city": "三亚",
        "price": 2100,
        "stops": 0,
        "duration": "3h40m",
    },
    {
        "flight_no": "HU7177",
        "airline": "海南航空",
        "departure_time": "18:10",
        "arrival_time": "22:00",
        "departure_city": "北京",
        "arrival_city": "成都",
        "price": 1580,
        "stops": 0,
        "duration": "2h50m",
    },
    {
        "flight_no": "ZH9831",
        "airline": "深圳航空",
        "departure_time": "11:30",
        "arrival_time": "14:15",
        "departure_city": "深圳",
        "arrival_city": "西安",
        "price": 1250,
        "stops": 0,
        "duration": "2h45m",
    },
    {
        "flight_no": "ZH9855",
        "airline": "深圳航空",
        "departure_time": "16:00",
        "arrival_time": "18:20",
        "departure_city": "深圳",
        "arrival_city": "昆明",
        "price": 1320,
        "stops": 0,
        "duration": "2h20m",
    },
    {
        "flight_no": "MF8501",
        "airline": "厦门航空",
        "departure_time": "08:00",
        "arrival_time": "09:40",
        "departure_city": "厦门",
        "arrival_city": "上海",
        "price": 880,
        "stops": 0,
        "duration": "1h40m",
    },
    {
        "flight_no": "MF8621",
        "airline": "厦门航空",
        "departure_time": "15:30",
        "arrival_time": "17:50",
        "departure_city": "厦门",
        "arrival_city": "杭州",
        "price": 920,
        "stops": 0,
        "duration": "1h20m",
    },
    {
        "flight_no": "9C8841",
        "airline": "春秋航空",
        "departure_time": "06:40",
        "arrival_time": "08:50",
        "departure_city": "上海",
        "arrival_city": "厦门",
        "price": 620,
        "stops": 0,
        "duration": "2h10m",
    },
    {
        "flight_no": "9C8823",
        "airline": "春秋航空",
        "departure_time": "21:30",
        "arrival_time": "23:55",
        "departure_city": "上海",
        "arrival_city": "重庆",
        "price": 750,
        "stops": 0,
        "duration": "2h25m",
    },
    {
        "flight_no": "HO1191",
        "airline": "吉祥航空",
        "departure_time": "10:15",
        "arrival_time": "13:30",
        "departure_city": "上海",
        "arrival_city": "昆明",
        "price": 1280,
        "stops": 1,
        "duration": "3h15m",
    },
    {
        "flight_no": "HO1235",
        "airline": "吉祥航空",
        "departure_time": "14:00",
        "arrival_time": "17:10",
        "departure_city": "上海",
        "arrival_city": "三亚",
        "price": 1750,
        "stops": 0,
        "duration": "3h10m",
    },
]
